baseurl = "http://embedded-elixir.com/"
languageCode = "en-us"
title = "Embedded Elixir"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "embedded-elixir"
googleAnalytics = "UA-16709386-6"

[Params]
  subtitle = "News and Articles about Elixir on Embedded Systems"
  logo = "images/logo.png"
  favicon = "images/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  comments = true

[Author]
  name = "Curated by Frank Hunleth"
  #github = "fhunleth"
  #twitter = "fhunleth" # Why doesn't this work???

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3
